#!/usr/bin/env bash
#
# Get the shell-friendly equivalent of a string.
#

usage() {
    cat <<EOF
Usage: ${0##*/} [options] STRING
Get the shell-friendly equivalent of a string.

  Options:
    -h          display this help message
EOF
}

while getopts "h" opt; do
    case $opt in
        h) # display help
            usage
            exit 0
    esac
done



if [ -z "$@" ]; then
    echo "${0##*/}: error: no arguments given"
    exit 1
fi



echo "$@" | \
    sed -e "s/[\.;':,()!?-]//g" \
        -e "s/&/and/g"          \
        -e "s/ /-/g"            \
        -e "s/\(.*\)/\L\1/g"
      # 1. remove punctuation
      # 2. '&' -> 'and'
      # 3. ' ' -> '-'
      # 4. to lowercase
